import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { IconLoader, IconSearch, Input } from '@supabase/ui'
import React, { useEffect, useState } from 'react'
import axios from "axios";
import { useRouter } from 'next/router'

export async function getStaticProps() {
  return {
    props: { title: 'My Title', content: '...' }
  }
}



function Home(title: String) {
  const router = useRouter()
  let [employees, setEmployees] = useState<any>([])
  const searchPartners = async (search: string) => {
    if (search.length === 0) {
      setEmployees([])
    }
    if (search.length >= 2) {
      await axios("https://api.themoviedb.org/3/search/tv?api_key=" + process.env.NEXT_PUBLIC_TMDB + "&language=en-US&page=1&query=" + search + "&include_adult=false").then(
        (res) => {
          const json = res.data;
          let totalResults = 0
          let searchResults = []
          for (let i = 0; i < json.results.length; ++i) {
            if (totalResults === 5) {
              break
            }
            let showName = json.results[i]['name'];
            let showID = json.results[i]['id']
            let posterPath = "https://image.tmdb.org/t/p/w500" + json.results[i]['poster_path']
            searchResults.push([showName, showID, posterPath])
            totalResults += 1
          }
          setEmployees(searchResults || [])
        }
      )

    }
    return 'Show Found!'
  }

  var employeeslist = employees
  return (
    <div className={styles.container}>
      <Head>
        <title>ScatterTV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
        <a>ScatterTV</a>
      </h1>

      <main className={styles.main}>
        <Input
          size="small"
          icon={<IconSearch />}
          placeholder="Search..."
          type="text"
          // className="md:w-1/2"
          onChange={(e) => {
            searchPartners(e.target.value)
          }
          }
          actions={
            (
              <span className="mr-1 animate-spin text-white">
                <IconLoader />
              </span>
            )
          }
        />

        <div className="hidden lg:block">
          <table >
            <tbody>
              {employeeslist.map(emp => (
                <tr key={emp}>
                  <td className={styles.resultCellImg} onClick={() => {
                  }}><img width='75px' src={emp[2]}></img></td>
                  <td className={styles.resultCellName} onClick={() => {
                    router.push('/shows/'+emp[1])

                  }}>{emp[0]}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>



        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
export default Home